version: "3.8"

services:

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: condo_app
      DB_PORT: 3306
      PORT: 3000
    volumes:
      - ./backend:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: condo_app
    ports:
      - "3306:3306"
    command: 
      - --default-time-zone=+07:00
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake   
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: